# Harbor Container Updater - Dependency Review Configuration
# GitHub dependency review action configuration

# Fail if vulnerabilities are found at or above this level
fail-on-severity: high # Allow moderate for now, block high/critical

# Allow these licenses
allowed-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - GPL-3.0
  - PSF-2.0 # Python Software Foundation
  - Apache # Apache License variants
  - BSD # BSD License variants

# Known packages with license detection issues but safe licenses
license-allowlist:
  - cryptography # Actually Apache-2.0/BSD but sometimes detected as null
  - packaging # Actually Apache-2.0/BSD but sometimes detected as null
  - python-dateutil # Actually Apache-2.0/BSD but sometimes detected as null
  - structlog # Actually Apache-2.0/MIT but sometimes detected as null

# Allow moderate vulnerabilities for now (will address in security review)
vulnerability-check: true
fail-on-scopes:
  - runtime
  - development

# Comment if vulnerabilities are found but allowed
comment-summary-in-pr: true

# Configuration for GitHub Actions dependency review
deny-licenses:
  - GPL-2.0 # Incompatible with MIT project
  - AGPL-3.0 # Incompatible with MIT project
  - LGPL-2.1 # Potentially problematic

allow-dependencies-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - PSF-2.0
