# Harbor Container Updater - Pre-commit Hooks Configuration
# Ensures code quality and consistency before commits

repos:
  # =============================================================================
  # Basic file checks and formatting
  # =============================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # File formatting
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: ^(node_modules/|\.git/|build/|dist/|.*\.min\.(js|css)$)
      - id: end-of-file-fixer
        exclude: ^(node_modules/|\.git/|build/|dist/|.*\.min\.(js|css)$|.*\.(png|jpg|jpeg|gif|ico|svg|woff|woff2|eot|ttf)$)
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^(node_modules/|\.git/|build/|dist/)

      # File validation
      - id: check-yaml
        exclude: ^(node_modules/|\.git/)
      - id: check-toml
        exclude: ^(node_modules/|\.git/)
      - id: check-json
        exclude: ^(node_modules/|\.git/|.*\.min\.json$)
      - id: check-xml
        exclude: ^(node_modules/|\.git/)

      # Git and merge checks
      - id: check-added-large-files
        args: [--maxkb=1000] # Prevent files larger than 1MB
        exclude: ^(node_modules/|\.git/)
      - id: check-merge-conflict
      - id: forbid-new-submodules

      # Python specific
      - id: check-ast # Check Python syntax
        exclude: ^(node_modules/|migrations/versions/)
      - id: debug-statements # Find debug statements
        exclude: ^(node_modules/|.*_test\.py|test_.*\.py|debug_.*\.py)
      - id: name-tests-test # Ensure test files are named correctly
        args: [--pytest-test-first]
        exclude: ^(node_modules/)

  # =============================================================================
  # Python code quality with Ruff (replaces flake8, isort, etc.)
  # =============================================================================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        name: ruff-check
        args: [--fix, --exit-zero] # Don't fail even when fixes are applied

      - id: ruff-format
        name: ruff-format

  # =============================================================================
  # Code formatting with Black - DISABLED (using Ruff instead)
  # =============================================================================
  # - repo: https://github.com/psf/black
  #   rev: 25.1.0
  #   hooks:
  #     - id: black
  #       name: black-formatter
  #       language_version: python3.13:

  # =============================================================================
  # Type checking with mypy
  # =============================================================================
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        name: mypy-type-check
        additional_dependencies:
          - types-python-dateutil>=2.8.0
          - types-requests>=2.31.0
          - types-PyYAML>=6.0.12
          - sqlalchemy[mypy]>=2.0.0
          - pydantic-settings>=2.1.0
          - psutil>=5.9.0
          - pyyaml>=6.0
          - fastapi>=0.104.0
          - uvicorn>=0.24.0
          - httpx>=0.25.0
        args: [--strict, --ignore-missing-imports]
        exclude: ^(migrations/|tests/fixtures/|.*_test\.py|test_.*\.py|debug_.*\.py|simple_.*\.py|validate_.*\.py|scripts/.*\.py)$

  # =============================================================================
  # Security scanning
  # =============================================================================
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit-security-check
        args: [--configfile, bandit.yaml, --recursive, app/]
        exclude: ^(tests/|.*_test\.py|test_.*\.py|debug_.*\.py|simple_.*\.py|scripts/.*\.py)$

  # =============================================================================
  # Documentation and markdown
  # =============================================================================
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: markdown-lint
        args: [--fix]
        exclude: ^(CHANGELOG\.md|\.github/|docs/examples/)

  # =============================================================================
  # Docker and YAML validation
  # =============================================================================
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: dockerfile-lint
        files: ^.*Dockerfile.*$
        args: [--ignore, DL3008, --ignore, DL3013] # Ignore version pinning warnings

  # =============================================================================
  # Secrets detection
  # =============================================================================
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: |
          (?x)^(
            \.env\.example|
            \.env\.development|
            package-lock\.json|
            pnpm-lock\.yaml|
            yarn\.lock|
            tests/fixtures/.*|
            .*_test\.py|
            test_.*\.py|
            debug_.*\.py|
            simple_.*\.py
          )$

  # =============================================================================
  # YAML formatting and validation
  # =============================================================================
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier-yaml
        files: \.(yaml|yml)$
        args: [--write]
        exclude: ^(\.github/workflows/|config/examples/)

  # =============================================================================
  # Python import sorting (additional check beyond ruff)
  # =============================================================================
  #- repo: https://github.com/pycqa/isort
  #  rev: 5.13.2
  #  hooks:
  #    - id: isort
  #      name: isort-import-sort
  #      args: [--profile=black, --line-length=88, --multi-line=3]
  #      exclude: ^(migrations/|.*_test\.py|test_.*\.py|debug_.*\.py|simple_.*\.py)$

  # =============================================================================
  # Python docstring formatting - DISABLED during development
  # =============================================================================
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.3.0
  #   hooks:
  #     - id: pydocstyle
  #       name: pydocstyle-docstring-check
  #       args: [--convention=google]
  #       exclude: ^(tests/|migrations/|.*_test\.py|test_.*\.py|debug_.*\.py|simple_.*\.py|validate_.*\.py)$

  # =============================================================================
  # Additional Python quality checks
  # =============================================================================
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        name: ruff-additional-checks
        args:
          [--select=F, E, W, I, N, UP, B, A, C4, DTZ, T20, PYI, PT, RUF, --fix]
        exclude: ^(migrations/|.*_test\.py|test_.*\.py|debug_.*\.py|simple_.*\.py)$

# =============================================================================
# Pre-commit CI Configuration
# =============================================================================
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: "main"
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false

# =============================================================================
# Development and Testing Exclusions
# =============================================================================
default_stages: [pre-commit, pre-push]
fail_fast: false

exclude: |
  (?x)^(
    # Version control
    \.git/.*|

    # Build and distribution
    build/.*|
    dist/.*|
    \.eggs?/.*|
    .*\.egg-info/.*|

    # Node.js (if present)
    node_modules/.*|

    # Cache directories
    __pycache__/.*|
    \.mypy_cache/.*|
    \.pytest_cache/.*|
    \.ruff_cache/.*|

    # Virtual environments
    venv/.*|
    \.venv/.*|
    env/.*|

    # IDE files
    \.vscode/.*|
    \.idea/.*|

    # OS files
    \.DS_Store|
    Thumbs\.db|

    # Log files
    \.log$|
    logs/.*|

    # Database files
    \.db$|
    \.sqlite$|
    \.sqlite3$|

    # Backup files
    .*\.bak$|
    .*\.backup$|

    # Temporary files
    \.tmp$|
    \.temp$|

    # Development and testing scripts (specific exclusions)
    simple_env_test\.py|
    test_config\.py|
    debug_test_config\.py|
    validate_config\.py|

    # Migration files
    migrations/versions/.*\.py$
  )$
