# Harbor Container Updater - Pre-commit Hooks Configuration
# Ensures code quality and consistency before commits

repos:
  # =============================================================================
  # Basic file checks and formatting
  # =============================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # File formatting
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]

      # File validation
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-xml

      # Git and merge checks
      - id: check-added-large-files
        args: [--maxkb=1000]  # Prevent files larger than 1MB
      - id: check-merge-conflict
      - id: forbid-new-submodules

      # Python specific
      - id: check-ast  # Check Python syntax
      - id: debug-statements  # Find debug statements
      - id: name-tests-test  # Ensure test files are named correctly
        args: [--pytest-test-first]

  # =============================================================================
  # Python code quality with Ruff (replaces flake8, isort, etc.)
  # =============================================================================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      # Linting
      - id: ruff-check
        name: ruff-check
        args: [--fix, --exit-non-zero-on-fix]

      # Import sorting
      - id: ruff-format
        name: ruff-format

  # =============================================================================
  # Code formatting with Black
  # =============================================================================
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black-formatter
        language_version: python3.13

  # =============================================================================
  # Type checking with mypy
  # =============================================================================
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        name: mypy-type-check
        additional_dependencies:
          - types-python-dateutil
          - types-requests
          - sqlalchemy[mypy]
        args: [--strict, --ignore-missing-imports]
        exclude: ^(migrations/|tests/fixtures/)

  # =============================================================================
  # Security scanning
  # =============================================================================
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit-security-check
        exclude: ^tests/

  # =============================================================================
  # Documentation and markdown
  # =============================================================================
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: markdown-lint
        args: [--fix]
        exclude: ^(CHANGELOG\.md|\.github/)

  # =============================================================================
  # Docker and YAML validation
  # =============================================================================
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: dockerfile-lint
        files: Dockerfile.*

  # =============================================================================
  # Secrets detection
  # =============================================================================
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets
        args: [ '--baseline', '.secrets.baseline' ]
        exclude: |
          (?x)^(
            \.env\.example|
            \.env\.development|
            package-lock\.json|
            pnpm-lock\.yaml|
            yarn\.lock|
            tests/fixtures/.*
          )$

# =============================================================================
# Pre-commit configuration
# =============================================================================
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
