---
# deploy/docker/docker-compose.yml
# Harbor Production Deployment - Enhanced Security

services:
  harbor:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    image: harbor/harbor:latest
    container_name: harbor
    restart: unless-stopped

    # Security options
    security_opt:
    - no-new-privileges:true
    cap_drop:
    - ALL
    cap_add:
    - NET_BIND_SERVICE    # Only if needed for port binding
    read_only: true  # Read-only root filesystem
    tmpfs:
    - /tmp:size=100M,mode=1777
    - /run:size=10M,mode=755
    - /app/.cache:size=50M,mode=755

    # Run as non-root user
    user: 1000:1000

    ports:
    - 8080:8080

    volumes:
      # Docker socket (read-only)
    - /var/run/docker.sock:/var/run/docker.sock:ro
      # Persistent data (writable)
    - harbor_data:/app/data:rw
      # Logs (writable)
    - harbor_logs:/app/logs:rw
      # Config (read-only)
    - ./config:/app/config:ro

    environment:
    - HARBOR_MODE=homelab
    - LOG_LEVEL=INFO
    - ENABLE_AUTO_DISCOVERY=true
    - DATABASE_URL=sqlite:////app/data/harbor.db
    - HARBOR_TIMEZONE=${TZ:-UTC}
    - DEFAULT_CHECK_INTERVAL_SECONDS=86400
    - MAX_CONCURRENT_UPDATES=2

    labels:
    - harbor.exclude=true
    - com.harbor.deployment=homelab

    healthcheck:
      test: [CMD, python, scripts/health_check.py]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

volumes:
  harbor_data:
    driver: local
    labels:
    - com.harbor.description=Harbor persistent data
  harbor_logs:
    driver: local
    labels:
    - com.harbor.description=Harbor application logs

networks:
  default:
    name: harbor_network
    driver: bridge
