---
# docker-compose.yml
# Harbor Container Updater - Production Deployment (Home Lab Optimized)
version: '3.8'

services:
  harbor:
    build:
      context: .  # Build from project root
      dockerfile: deploy/docker/Dockerfile
    image: harbor/harbor:latest
    container_name: harbor
    restart: unless-stopped

    # Security options (matching the enhanced Dockerfile)
    security_opt:
    - no-new-privileges:true
    cap_drop:
    - ALL
    cap_add:
    - CHOWN        # Needed for file ownership operations
    - SETUID       # Needed for user switching
    - SETGID       # Needed for group switching
    read_only: true  # Read-only root filesystem
    tmpfs:
    - /tmp:size=100M,mode=1777
    - /run:size=10M,mode=755
    - /app/.cache:size=50M,mode=755

    # Run as non-root user (matching Dockerfile)
    user: 1000:1000

    ports:
    - 8080:8080

    volumes:
      # Docker socket for container management (read-only)
    - /var/run/docker.sock:/var/run/docker.sock:ro
      # Persistent data storage (writable by UID 1000)
    - harbor_data:/app/data:rw
      # Logs persistence (writable by UID 1000)
    - harbor_logs:/app/logs:rw
      # Optional: Custom configuration (read-only)
      # - ./config:/app/config:ro

    environment:
      # Deployment profile
    - HARBOR_MODE=homelab

      # Security environment
    - PYTHONHASHSEED=random

      # Logging
    - LOG_LEVEL=INFO
    - LOG_RETENTION_DAYS=14

      # Core features
    - ENABLE_AUTO_DISCOVERY=true
    - ENABLE_GETTING_STARTED=true
    - ENABLE_SIMPLE_MODE=true

      # Database
    - DATABASE_URL=sqlite:////app/data/harbor.db

      # Timezone
    - HARBOR_TIMEZONE=${TZ:-UTC}

      # Update configuration
    - DEFAULT_CHECK_INTERVAL_SECONDS=86400
    - DEFAULT_UPDATE_TIME=03:00
    - MAX_CONCURRENT_UPDATES=2

      # Security (home lab defaults)
    - REQUIRE_HTTPS=false
    - SESSION_TIMEOUT_HOURS=168

      # Resource optimization
    - HARBOR_MAX_WORKERS=2
    - DATABASE_POOL_SIZE=5

    labels:
    - harbor.exclude=true
    - com.harbor.deployment=homelab
    - com.harbor.version=${VERSION:-0.1.0-M0}

    healthcheck:
      test: [CMD, python, scripts/health_check.py]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

volumes:
  harbor_data:
    driver: local
    labels:
    - com.harbor.description=Harbor persistent data
    - com.harbor.owner=1000      # Document expected ownership

  harbor_logs:
    driver: local
    labels:
    - com.harbor.description=Harbor application logs
    - com.harbor.owner=1000      # Document expected ownership

networks:
  default:
    name: harbor_network
    driver: bridge
