---
# docker-compose.prod.yml
# Harbor Container Updater - Production deployment with enhanced security

services:
  # Docker socket proxy
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: harbor-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      VOLUMES: 1
      INFO: 1
      VERSION: 1
      POST: 1
      BUILD: 0
      COMMIT: 0
      EXEC: 0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - harbor-backend
    security_opt:
    - no-new-privileges:true
    - apparmor:docker-default
    cap_drop:
    - ALL
    read_only: true
    tmpfs:
    - /tmp:size=10M

  harbor:
    build:
      context: .  # Build from project root
      dockerfile: deploy/docker/Dockerfile
      secrets:
      - pip_index_url
    image: harbor/harbor:latest
    container_name: harbor
    restart: unless-stopped
    depends_on:
    - socket-proxy

    # Maximum security
    security_opt:
    - no-new-privileges:true
    - apparmor:harbor-container    # Custom profile
    - seccomp:deploy/security/seccomp-harbor.json
    cap_drop:
    - ALL
    read_only: true
    tmpfs:
    - /tmp:size=100M,mode=1777
    - /run:size=10M,mode=755
    - /app/.cache:size=50M,mode=755

    user: 1000:1000

    ports:
    - 127.0.0.1:8080:8080

    volumes:
    - harbor_data:/app/data:rw
    - harbor_logs:/app/logs:rw
    - ./config/production.yaml:/app/config/production.yaml:ro
    - ./deploy/security/apparmor-harbor:/etc/apparmor.d/harbor:ro

    environment:
    - HARBOR_MODE=production
    - DOCKER_HOST=tcp://socket-proxy:2375
    - PYTHONHASHSEED=random
    - HARBOR_SECRET_KEY_FILE=/run/secrets/harbor_secret

    networks:
    - harbor-backend
    - harbor-frontend

    secrets:
    - harbor_secret

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

networks:
  harbor-backend:
    internal: true
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.0.0/24
  harbor-frontend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.29.0.0/24

volumes:
  harbor_data:
    driver: local
  harbor_logs:
    driver: local

secrets:
  harbor_secret:
    external: true
  pip_index_url:
    file: ./secrets/pip_index_url.txt
