# Home Lab with Monitoring Example
# Harbor with Prometheus and Grafana
version: "3.8"

services:
  harbor:
    image: ghcr.io/deusextaco/harbor:latest
    container_name: harbor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - harbor_data:/app/data
    environment:
      - HARBOR_MODE=homelab
      - ENABLE_METRICS=true
    labels:
      - "harbor.exclude=true"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  harbor_data:
  prometheus_data:
  grafana_data:
