name: 🚀 Feature Request
description: Suggest an idea for Harbor
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Harbor is designed to be home lab friendly first, with enterprise features added progressively.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been suggested before
          required: true
        - label: I have reviewed the roadmap to see if this feature is already planned
          required: true
        - label: This feature aligns with Harbor's goal of being home lab friendly
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Container Discovery & Management
        - Update Engine & Strategies
        - Web Interface & User Experience
        - Security & Authentication
        - Monitoring & Observability
        - Registry Integration
        - Scheduling & Automation
        - Deployment & Configuration
        - API & Integrations
        - Documentation & Help
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: target-users
    attributes:
      label: Target Users
      description: Who would primarily benefit from this feature?
      options:
        - Home lab users (primary focus)
        - Enterprise users
        - Both home lab and enterprise
        - Developers/Contributors
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the current pain point?
      placeholder: Describe the problem you're experiencing or the gap you've identified
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen? Describe your ideal solution.
      placeholder: Describe how you envision this feature working
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? How do other tools handle this?
      placeholder: Describe alternative solutions you've thought about

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (UI change, configuration option)
        - Medium (new API endpoint, minor feature)
        - Complex (major new functionality)
        - Very Complex (architectural changes)
        - Unknown

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (blocking my use of Harbor)
        - High (would significantly improve my workflow)
        - Medium (nice to have improvement)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case Description
      description: |
        Describe your specific use case in detail. This helps us understand the context and requirements.
      placeholder: |
        Example: "I run 15 containers on my Raspberry Pi 4 for my home lab. Currently I have to..."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        What would need to be true for you to consider this feature complete?
      placeholder: |
        - Feature should...
        - Users should be able to...
        - The system should...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Interest
      options:
        - label: I would be interested in contributing to the implementation of this feature
        - label: I would be willing to test beta versions of this feature
        - label: I would be willing to provide detailed feedback during development

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, mockups, or examples that would help explain this feature request.
