---
# Harbor Container Updater - Home Lab Configuration
# Optimized for home lab environments with zero-config deployment
# Following Harbor architecture design principles

# =============================================================================
# Deployment Profile
# =============================================================================
deployment:
  profile: homelab
  description: Home lab optimized for ease of use and resource efficiency
  auto_setup: true # Enable automatic first-run setup
  show_welcome: true # Show welcome message on startup

# =============================================================================
# Application Settings
# =============================================================================
app:
  name: Harbor Container Updater
  debug: false
  host: 0.0.0.0
  port: 8080

# =============================================================================
# Database Configuration (SQLite for zero-config)
# =============================================================================
database:
  type: sqlite
  # URL auto-generated as: sqlite:///data/harbor.db
  pool_size: 5
  max_overflow: 2
  pool_timeout: 30
  echo_sql: false # Disable SQL logging for cleaner logs

  # Home lab backup settings
  backup_enabled: true
  backup_retention_days: 7 # Keep 1 week of backups
  backup_schedule: 0 2 * * *   # Daily at 2 AM

# =============================================================================
# Security Settings (Relaxed for home networks)
# =============================================================================
security:
  # Network security
  require_https: false # HTTP OK for internal networks
  session_timeout_hours: 168 # 1 week (convenient for home use)
  session_secure_cookies: false

  # Authentication
  api_key_required: false # Optional for home lab
  password_min_length: 6 # Reasonable minimum
  password_require_special: false

  # Rate limiting (generous for home use)
  api_rate_limit_per_hour: 1000

  # Future features (disabled in v1.0)
  mfa_enabled: false # TODO: M7+ Multi-factor authentication

# =============================================================================
# Container Update Settings (Conservative and safe)
# =============================================================================
updates:
  # Scheduling
  default_check_interval_seconds: 86400 # Daily checks
  default_update_time: 03:00   # 3 AM updates (low usage time)
  default_timezone: UTC # UTC for consistency

  # Concurrency (conservative for home hardware)
  max_concurrent_updates: 2 # Limit concurrent operations
  update_delay_seconds: 5 # Brief delay between updates

  # Safety settings
  default_health_check_timeout: 60 # 1 minute health check
  default_rollback_enabled: true # Always enable rollback
  rollback_timeout_seconds: 300 # 5 minute rollback timeout

  # Cleanup settings
  default_cleanup_enabled: true # Clean up old images
  default_cleanup_keep_images: 2 # Keep 2 previous versions
  cleanup_delay_hours: 24 # Wait 24h before cleanup

# =============================================================================
# Docker Runtime Settings
# =============================================================================
docker:
  # Connection
  host: unix:///var/run/docker.sock   # Direct socket (home lab default)
  # host: "tcp://docker-socket-proxy:2375"  # Use this for socket proxy
  timeout: 60 # API timeout

  # Discovery
  discovery_interval_seconds: 300 # Check every 5 minutes
  include_stopped_containers: true # Include stopped containers

  # Safety patterns
  exclude_patterns:
  - harbor   # Exclude Harbor itself
  - '*_backup'   # Exclude backup containers
  - '*_migrate'   # Exclude migration containers
  - portainer*   # Exclude Portainer
  - watchtower*   # Exclude existing updaters

# =============================================================================
# Registry Settings (Public registries)
# =============================================================================
registry:
  # Client settings
  timeout_seconds: 30 # Registry request timeout
  retry_count: 3 # Retry failed requests

  # Caching (important for rate limits)
  cache_ttl_seconds: 3600 # 1 hour cache
  cache_size_mb: 50 # Cache size limit

  # Rate limiting (respect Docker Hub limits)
  rate_limit_calls_per_hour: 100 # Conservative limit

# =============================================================================
# Logging Settings (Simple for home lab)
# =============================================================================
logging:
  level: INFO # Informational logging
  format: text # Human-readable format

  # File logging
  to_file: true
  # file_path: "logs/harbor.log"           # Auto-generated
  rotation_size_mb: 10 # Rotate at 10MB
  retention_days: 14 # Keep 2 weeks of logs

  # Console logging
  to_console: true

# =============================================================================
# Resource Settings (Optimized for home hardware)
# =============================================================================
resources:
  max_memory_usage_mb: 256 # Conservative memory limit
  max_disk_usage_gb: 5 # Reasonable disk usage
  max_workers: 2 # Limit worker processes

# =============================================================================
# Feature Flags (v1.0 home lab focus)
# =============================================================================
features:
  # v1.0 Core features (always enabled)
  enable_auto_discovery: true # Automatic container discovery
  enable_metrics: true # Prometheus metrics
  enable_health_checks: true # Health monitoring

  # Home lab UX features
  show_getting_started: true # First-run wizard
  enable_simple_mode: true # Simplified interface
  auto_exclude_harbor: true # Don't update Harbor itself

  # Future features (disabled in v1.0)
  # Authentication enhancements (M7+)
  enable_mfa: false # TODO: M7+ Multi-factor auth
  enable_multi_user: false # TODO: M8+ Multiple users
  enable_rbac: false # TODO: M8+ Role-based access

  # Update strategy enhancements (M8+)
  enable_blue_green: false # TODO: M8+ Blue/green deployment
  enable_canary: false # TODO: M8+ Canary deployment

  # Runtime enhancements (M9+)
  enable_kubernetes: false # TODO: M9+ Kubernetes support
  enable_podman: false # TODO: M10+ Podman support

  # Integration enhancements (M7+)
  enable_slack: false # TODO: M7+ Slack notifications
  enable_email: false # TODO: M7+ Email notifications
  enable_ldap: false # TODO: M9+ LDAP authentication

# =============================================================================
# Maintenance and Operations
# =============================================================================
maintenance:
  # Maintenance windows
  maintenance_window_start: 02:00   # Start maintenance at 2 AM
  maintenance_window_end: 05:00   # End maintenance at 5 AM
  maintenance_days: [sunday] # Weekly maintenance on Sunday

  # Blackout periods (no updates during these times)
  blackout_periods: [] # No blackouts by default

  # Emergency controls
  global_pause_updates: false # Global update pause switch
  global_dry_run_mode: false # Global dry-run mode
  emergency_stop: false # Emergency stop all operations

# Continue with the rest of the file unchanged...
# (The remaining sections don't have any colon issues)
