# Harbor Container Updater - Production Configuration
# Enterprise-ready configuration for production environments
# Following Harbor architecture design principles

# =============================================================================
# Deployment Profile
# =============================================================================
deployment:
  profile: production
  description: "Enterprise production deployment with security and compliance"
  auto_setup: false # Require manual configuration
  show_welcome: false # Hide getting started wizard

# =============================================================================
# Application Settings
# =============================================================================
app:
  name: "Harbor Container Updater"
  debug: false # Never enable debug in production
  host: "0.0.0.0"
  port: 8080

# =============================================================================
# Database Configuration (PostgreSQL for enterprise scale)
# =============================================================================
database:
  type: postgresql
  # URL from environment: postgresql://user:pass@host:5432/harbor
  pool_size: 20 # Larger pool for enterprise load
  max_overflow: 10 # Higher overflow capacity
  pool_timeout: 60 # Longer timeout for production
  echo_sql: false # Never echo SQL in production

  # Enterprise backup settings
  backup_enabled: true
  backup_retention_days: 90 # Longer retention for compliance
  backup_schedule: "0 1 * * *" # Daily at 1 AM
  backup_encryption: true # TODO: M9+ Encrypt backups

# =============================================================================
# Security Settings (Enterprise-grade - CONSOLIDATED)
# =============================================================================
security:
  # Network security (strict)
  require_https: true # Mandatory HTTPS
  session_timeout_hours: 8 # 8 hour sessions (work day)
  session_secure_cookies: true

  # Authentication (strict)
  api_key_required: true # Mandatory API authentication
  password_min_length: 12 # Strong passwords required
  password_require_special: true
  password_require_upper: true # TODO: M7+ Uppercase required
  password_require_lower: true # TODO: M7+ Lowercase required
  password_require_digit: true # TODO: M7+ Digits required

  # Rate limiting (production scale)
  api_rate_limit_per_hour: 5000
  rate_limit_burst: 100 # TODO: M7+ Burst allowance

  # Future enterprise security features
  mfa_enabled: false # TODO: M7+ Enable in enterprise deployments
  mfa_required_for_admin: false # TODO: M7+ Require MFA for admins
  api_key_rotation_days: 90 # TODO: M8+ Rotate API keys
  audit_all_actions: true # TODO: M7+ Comprehensive audit logging

  # Access control (future)
  rbac_enabled: false # TODO: M8+ Role-based access
  fine_grained_permissions: false # TODO: M8+ Granular permissions

  # External authentication (future)
  ldap_enabled: false # TODO: M9+ LDAP integration
  saml_enabled: false # TODO: M9+ SAML SSO
  oauth_enabled: false # TODO: M9+ OAuth providers

  # Security monitoring
  failed_login_monitoring: true # TODO: M7+ Monitor failed logins
  suspicious_activity_detection: false # TODO: M8+ Anomaly detection

  # Data protection
  encrypt_sensitive_data: true # TODO: M9+ Encrypt sensitive fields
  secure_key_storage: true # TODO: M9+ Hardware security modules

  # Compliance settings
  compliance_mode: false # TODO: M9+ GDPR/SOX compliance mode
  data_retention_policy: 365 # TODO: M9+ Days to retain audit data

# =============================================================================
# Container Update Settings (Enterprise scale)
# =============================================================================
updates:
  # Scheduling (more frequent checks)
  default_check_interval_seconds: 21600 # Every 6 hours
  default_update_time: "02:00" # 2 AM updates (maintenance window)
  default_timezone: "UTC" # Always UTC for enterprise

  # Concurrency (higher for enterprise hardware)
  max_concurrent_updates: 10 # Higher concurrency
  update_delay_seconds: 0 # No delay needed

  # Safety settings (stricter)
  default_health_check_timeout: 120 # Longer health checks
  default_rollback_enabled: true # Always enable rollback
  rollback_timeout_seconds: 600 # 10 minute rollback timeout

  # Cleanup settings (keep more versions)
  default_cleanup_enabled: true
  default_cleanup_keep_images: 5 # Keep more versions for enterprise
  cleanup_delay_hours: 48 # Wait longer before cleanup

  # Enterprise update features
  require_approval: false # TODO: M10+ Manual approval for critical updates
  change_window_enforcement: true # TODO: M8+ Enforce maintenance windows
  dependency_ordering: false # TODO: M9+ Update containers in dependency order

# =============================================================================
# Docker Runtime Settings (Production)
# =============================================================================
docker:
  # Connection (socket proxy required for production)
  host: "tcp://docker-socket-proxy:2375" # Socket proxy mandatory
  timeout: 120 # Longer timeout for production

  # Discovery (optimized for large environments)
  discovery_interval_seconds: 600 # Every 10 minutes
  include_stopped_containers: true

  # Enterprise safety patterns
  exclude_patterns:
    - "harbor*" # Harbor components
    - "*_backup" # Backup containers
    - "*_migrate" # Migration containers
    - "*_proxy" # Infrastructure proxies
    - "*_lb" # Load balancers
    - "*database*" # Database containers
    - "*_db" # Database containers
    - "*postgres*" # PostgreSQL
    - "*mysql*" # MySQL
    - "*redis*" # Redis
    - "*elasticsearch*" # Elasticsearch
    - "*prometheus*" # Monitoring infrastructure
    - "*grafana*" # Monitoring infrastructure

# =============================================================================
# Registry Settings (Enterprise scale)
# =============================================================================
registry:
  # Client settings (higher timeouts for enterprise)
  timeout_seconds: 60 # Longer timeout
  retry_count: 5 # More retries

  # Caching (larger cache for performance)
  cache_ttl_seconds: 1800 # 30 minute cache
  cache_size_mb: 500 # Larger cache

  # Rate limiting (enterprise limits)
  rate_limit_calls_per_hour: 2000 # Higher limits

  # Enterprise registry features
  multi_registry_failover: true # TODO: M8+ Failover between registries
  registry_health_monitoring: true # TODO: M7+ Monitor registry health

# =============================================================================
# Logging Settings (Enterprise observability)
# =============================================================================
logging:
  level: INFO # Production logging level
  format: json # Structured logging for parsing

  # File logging (persistent)
  to_file: true
  rotation_size_mb: 50 # Larger log files
  retention_days: 90 # Longer retention for compliance

  # Console logging (for container orchestration)
  to_console: true

  # Audit logging
  audit_enabled: true # TODO: M7+ Separate audit logs
  audit_retention_days: 365 # TODO: M7+ 1 year audit retention

# =============================================================================
# Resource Settings (Enterprise hardware)
# =============================================================================
resources:
  max_memory_usage_mb: 2048 # 2GB memory limit
  max_disk_usage_gb: 100 # 100GB disk limit
  max_workers: auto # Auto-scale workers

# =============================================================================
# Feature Flags (Enterprise features enabled)
# =============================================================================
features:
  # v1.0 Core features
  enable_auto_discovery: true
  enable_metrics: true
  enable_health_checks: true

  # Enterprise UX (hide home lab features)
  show_getting_started: false # No wizard for production
  enable_simple_mode: false # Full interface
  auto_exclude_harbor: true # Still exclude Harbor

  # Future enterprise features (ready to enable)
  # Authentication enhancements (M7+)
  enable_mfa: false # TODO: M7+ Enable for enterprise
  enable_multi_user: false # TODO: M8+ Multiple users
  enable_rbac: false # TODO: M8+ Role-based access

  # Update strategy enhancements (M8+)
  enable_blue_green: false # TODO: M8+ Blue/green deployment
  enable_canary: false # TODO: M8+ Canary deployment
  enable_approval_workflow: false # TODO: M10+ Manual approvals

  # Runtime enhancements (M9+)
  enable_kubernetes: false # TODO: M9+ Kubernetes support
  enable_docker_swarm: false # TODO: M11+ Swarm support

  # Integration enhancements (M7+)
  enable_slack: false # TODO: M7+ Slack integration
  enable_email: false # TODO: M7+ Email notifications
  enable_ldap: false # TODO: M9+ LDAP authentication
  enable_saml: false # TODO: M9+ SAML SSO

  # Monitoring enhancements (M7+)
  enable_tracing: false # TODO: M7+ Distributed tracing
  enable_alerting: false # TODO: M7+ Alert manager
  enable_log_aggregation: false # TODO: M8+ ELK/Loki integration

  # Data features (M9+)
  enable_compliance_export: false # TODO: M9+ Compliance reporting
  enable_data_encryption: false # TODO: M9+ Database encryption

# =============================================================================
# High Availability (Future)
# =============================================================================
high_availability:
  # Load balancing
  enable_load_balancing: false # TODO: M8+ Load balancer support
  sticky_sessions: true # TODO: M8+ Session affinity

  # Clustering
  enable_clustering: false # TODO: M8+ Multi-instance clustering
  cluster_discovery: "kubernetes" # TODO: M8+ Cluster discovery method

  # Data replication
  database_replication: false # TODO: M9+ Database HA
  shared_storage: false # TODO: M9+ Shared storage for HA

# =============================================================================
# Compliance and Audit (Enterprise requirements)
# =============================================================================
compliance:
  # Audit requirements
  audit_all_operations: true # TODO: M7+ Comprehensive auditing
  audit_retention_years: 7 # TODO: M7+ 7 year retention
  audit_encryption: true # TODO: M9+ Encrypt audit logs

  # Data protection
  gdpr_compliance: false # TODO: M9+ GDPR compliance mode
  sox_compliance: false # TODO: M9+ SOX compliance mode
  pci_compliance: false # TODO: M9+ PCI DSS compliance

  # Access logging
  log_all_access: true # TODO: M7+ Log all API access
  log_data_access: true # TODO: M7+ Log data access
  log_admin_actions: true # TODO: M7+ Log admin actions

# =============================================================================
# Performance Tuning (Enterprise scale)
# =============================================================================
performance:
  # Database optimization
  database_connection_pooling: true
  database_query_caching: true # TODO: M8+ Query result caching
  database_index_optimization: true # TODO: M8+ Auto-optimize indexes

  # Application optimization
  async_processing: true # Async operations
  batch_operations: true # TODO: M8+ Batch multiple operations
  lazy_loading: true # Load features on demand

  # Caching strategy
  multi_layer_caching: true # TODO: M8+ Memory + Redis caching
  cache_warming: true # TODO: M8+ Pre-warm caches

  # Resource management
  auto_scaling: false # TODO: M9+ Auto-scale workers
  resource_monitoring: true # Monitor resource usage
  gc_optimization: true # Optimize garbage collection

# =============================================================================
# Monitoring and Alerting (Enterprise observability)
# =============================================================================
monitoring:
  # Metrics collection
  prometheus_enabled: true
  custom_metrics: false # TODO: M8+ User-defined metrics
  metrics_retention_days: 30

  # Health monitoring
  comprehensive_health_checks: true
  health_check_intervals: 30 # Check every 30 seconds
  dependency_health_checks: true # TODO: M7+ Check external dependencies

  # Alerting
  alerting_enabled: false # TODO: M7+ Alert manager integration
  alert_escalation: false # TODO: M7+ Alert escalation

  # Observability
  distributed_tracing: false # TODO: M7+ OpenTelemetry tracing
  apm_integration: false # TODO: M8+ APM integration

# =============================================================================
# Notification Settings (Enterprise scale)
# =============================================================================
notifications:
  # Channels (all disabled until implemented)
  email_enabled: false # TODO: M7+ Email notifications
  slack_enabled: false # TODO: M7+ Slack integration
  teams_enabled: false # TODO: M7+ Microsoft Teams
  webhook_enabled: true # Basic webhook support
  sms_enabled: false # TODO: M8+ SMS notifications

  # Notification rules
  notify_on_success: false # Don't spam on success
  notify_on_failure: true # Always notify on failures
  notify_on_rollback: true # Always notify on rollbacks

  # Escalation (future)
  escalation_enabled: false # TODO: M7+ Alert escalation
  escalation_timeout_minutes: 30 # TODO: M7+ Escalation timeout

# =============================================================================
# Integration Settings (Enterprise integrations)
# =============================================================================
integrations:
  # Container orchestration
  kubernetes:
    enabled: false # TODO: M9+ Kubernetes support
    namespace_discovery: true # TODO: M9+ Discover across namespaces
    rbac_integration: true # TODO: M9+ Use K8s RBAC

  # External services
  service_mesh:
    istio_integration: false # TODO: M10+ Istio support
    linkerd_integration: false # TODO: M10+ Linkerd support

  # CI/CD integration
  ci_cd:
    jenkins_integration: false # TODO: M8+ Jenkins integration
    gitlab_ci_integration: false # TODO: M8+ GitLab CI integration
    github_actions_integration: false # TODO: M8+ GitHub Actions

  # Infrastructure as Code
  iac:
    terraform_integration: false # TODO: M9+ Terraform provider
    ansible_integration: false # TODO: M9+ Ansible modules
    helm_integration: false # TODO: M9+ Helm chart updates

# =============================================================================
# Maintenance and Operations (Enterprise requirements)
# =============================================================================
maintenance:
  # Maintenance windows (strict enforcement)
  maintenance_window_start: "01:00" # 1 AM maintenance start
  maintenance_window_end: "04:00" # 4 AM maintenance end
  maintenance_days: ["sunday"] # Sunday maintenance
  enforce_maintenance_windows: true # TODO: M8+ Strict enforcement

  # Blackout periods (no updates during business critical times)
  blackout_periods:
    - name: "Business Hours"
      start_time: "08:00"
      end_time: "18:00"
      days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
    - name: "Month End"
      start_date: "28" # TODO: M8+ Date-based blackouts
      end_date: "2" # TODO: M8+ Next month 2nd

  # Emergency controls
  global_pause_updates: false # Global pause switch
  global_dry_run_mode: false # Global dry-run mode
  emergency_stop: false # Emergency stop button

  # Change management
  require_change_tickets: false # TODO: M10+ ITSM integration
  change_approval_required: false # TODO: M10+ Approval workflows

# =============================================================================
# Network and Infrastructure
# =============================================================================
network:
  # Load balancing
  load_balancer_integration: false # TODO: M8+ LB health checks
  session_affinity: true # TODO: M8+ Sticky sessions

  # TLS configuration
  tls_min_version: "1.2" # Minimum TLS version
  cipher_suites: "modern" # TODO: M7+ Modern cipher suites only

  # Proxy configuration
  trust_proxy_headers: true # Trust X-Forwarded headers
  proxy_timeout_seconds: 300 # 5 minute proxy timeout

# =============================================================================
# Enterprise Integrations
# =============================================================================
enterprise:
  # Identity providers
  active_directory: false # TODO: M9+ AD integration
  ldap_servers: [] # TODO: M9+ LDAP server list
  saml_providers: [] # TODO: M9+ SAML identity providers

  # Service management
  itsm_integration: false # TODO: M10+ ServiceNow/Jira integration
  cmdb_integration: false # TODO: M10+ Configuration management DB

  # Compliance frameworks
  frameworks:
    gdpr: false # TODO: M9+ GDPR compliance
    sox: false # TODO: M9+ SOX compliance
    pci_dss: false # TODO: M9+ PCI DSS compliance
    iso27001: false # TODO: M9+ ISO 27001 compliance

# =============================================================================
# Performance and Scaling
# =============================================================================
scaling:
  # Horizontal scaling
  horizontal_scaling: false # TODO: M9+ Multi-instance deployment
  auto_scaling_metrics: ["cpu", "memory", "request_rate"] # TODO: M9+ Scaling triggers

  # Resource optimization
  memory_optimization: true # Optimize memory usage
  cpu_optimization: true # Optimize CPU usage
  network_optimization: true # Optimize network usage

  # Cache optimization
  redis_caching: false # TODO: M8+ Redis for caching
  distributed_caching: false # TODO: M9+ Distributed cache
  cache_warming: false # TODO: M8+ Pre-warm caches

# =============================================================================
# Backup and Disaster Recovery
# =============================================================================
backup:
  # Database backups
  automated_backups: true
  backup_frequency: "daily" # daily, hourly, weekly
  backup_retention_policy: "90d" # 90 days retention
  backup_encryption: true # TODO: M9+ Encrypt backups
  backup_compression: true

  # Offsite backup
  offsite_backup_enabled: false # TODO: M9+ Cloud backup
  backup_verification: true # TODO: M8+ Verify backup integrity

  # Disaster recovery
  disaster_recovery_plan: false # TODO: M10+ DR procedures
  rto_target_hours: 4 # TODO: M10+ Recovery time objective
  rpo_target_hours: 1 # TODO: M10+ Recovery point objective

# =============================================================================
# Documentation and Support
# =============================================================================
help:
  documentation_url: "https://harbor-docs.dev/enterprise"
  deployment_guide: "https://harbor-docs.dev/enterprise/deployment"
  security_guide: "https://harbor-docs.dev/enterprise/security"
  troubleshooting: "https://harbor-docs.dev/enterprise/troubleshooting"
  enterprise_support: "https://harbor-docs.dev/enterprise/support"

  # Enterprise support
  show_tooltips: false # Minimal UI hints for enterprise
  show_examples: true # Show configuration examples
  show_recommendations: false # Hide recommendations (admins know what they want)

# =============================================================================
# Version and Compatibility
# =============================================================================
config_version: "1.0" # Configuration schema version
compatible_harbor_versions: ["0.1.0+"] # Compatible Harbor versions
last_updated: "2024-01-15" # Configuration last updated
environment_validation_required: true # Validate environment on startup
