---
# Harbor Container Updater - Production Configuration
# Enterprise-ready configuration for production environments
# Following Harbor architecture design principles

# =============================================================================
# Deployment Profile
# =============================================================================
deployment:
  profile: production
  description: Enterprise production deployment with security and compliance
  auto_setup: false # Require manual configuration
  show_welcome: false # Hide getting started wizard

# =============================================================================
# Application Settings
# =============================================================================
app:
  name: Harbor Container Updater
  debug: false # Never enable debug in production
  host: 0.0.0.0
  port: 8080

# =============================================================================
# Database Configuration (PostgreSQL for enterprise scale)
# =============================================================================
database:
  type: postgresql
  # URL from environment: postgresql://user:pass@host:5432/harbor
  pool_size: 20 # Larger pool for enterprise load
  max_overflow: 10 # Higher overflow capacity
  pool_timeout: 60 # Longer timeout for production
  echo_sql: false # Never echo SQL in production

  # Enterprise backup settings
  backup_enabled: true
  backup_retention_days: 90 # Longer retention for compliance
  backup_schedule: 0 1 * * *   # Daily at 1 AM
  backup_encryption: true # TODO: M9+ Encrypt backups

# Continue with security section unchanged until updates section...

# =============================================================================
# Container Update Settings (Enterprise scale)
# =============================================================================
updates:
  # Scheduling (more frequent checks)
  default_check_interval_seconds: 21600 # Every 6 hours
  default_update_time: 02:00   # 2 AM updates (maintenance window)
  default_timezone: UTC # Always UTC for enterprise

  # Rest of updates section unchanged...

# Continue until maintenance section...

# =============================================================================
# Maintenance and Operations (Enterprise requirements)
# =============================================================================
maintenance:
  # Maintenance windows (strict enforcement)
  maintenance_window_start: 01:00   # 1 AM maintenance start
  maintenance_window_end: 04:00   # 4 AM maintenance end
  maintenance_days: [sunday] # Sunday maintenance
  enforce_maintenance_windows: true # TODO: M8+ Strict enforcement

  # Blackout periods (no updates during business critical times)
  blackout_periods:
  - name: Business Hours
    start_time: 08:00
    end_time: 18:00
    days: [monday, tuesday, wednesday, thursday, friday]
  - name: Month End
    start_date: '28'   # TODO: M8+ Date-based blackouts
    end_date: '2'   # TODO: M8+ Next month 2nd

  # Rest of the file continues unchanged...
