# .github/workflows/cache-warmer.yml
name: Cache Warmer

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:

jobs:
  warm-docker-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build cache layers
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/docker/Dockerfile.dev
          platforms: linux/amd64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: builder  # Only build to builder stage
