# New reusable workflow: .github/workflows/cache-results.yml
name: Cache Test Results

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
    outputs:
      cache-hit:
        value: ${{ jobs.check-cache.outputs.cache-hit }}

jobs:
  check-cache:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/cache@v4
        id: cache
        with:
          path: test-results
          key: ${{ inputs.cache-key }}-${{ github.sha }}
          restore-keys: |
            ${{ inputs.cache-key }}-
